title: Multidisciplinary Approaches to Co-Creating Trustworthy Autonomous Systems
description: ICRA 2023 Workshop
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts # Apply the default values below only to posts
    values:
      image: /docs/assets/images/tas_logo.png
